{
    "mtlsRootUrl": "https://www.mtls.googleapis.com/",
    "auth": {
        "oauth2": {
            "scopes": {
                "https://www.googleapis.com/auth/drive.photos.readonly": {
                    "description": "View the photos, videos and albums in your Google Photos"
                },
                "https://www.googleapis.com/auth/drive.scripts": {
                    "description": "Modify your Google Apps Script scripts' behavior"
                },
                "https://www.googleapis.com/auth/drive.metadata.readonly": {
                    "description": "See information about your Google Drive files"
                },
                "https://www.googleapis.com/auth/drive.apps.readonly": {
                    "description": "View your Google Drive apps"
                },
                "https://www.googleapis.com/auth/drive.meet.readonly": {
                    "description": "See and download your Google Drive files that were created or edited by Google Meet."
                },
                "https://www.googleapis.com/auth/drive.file": {
                    "description": "See, edit, create, and delete only the specific Google Drive files you use with this app"
                },
                "https://www.googleapis.com/auth/drive": {
                    "description": "See, edit, create, and delete all of your Google Drive files"
                },
                "https://www.googleapis.com/auth/drive.metadata": {
                    "description": "View and manage metadata of files in your Google Drive"
                },
                "https://www.googleapis.com/auth/drive.readonly": {
                    "description": "See and download all your Google Drive files"
                },
                "https://www.googleapis.com/auth/drive.appdata": {
                    "description": "See, create, and delete its own configuration data in your Google Drive"
                }
            }
        }
    },
    "servicePath": "drive/v2/",
    "name": "drive",
    "batchPath": "batch/drive/v2",
    "basePath": "/drive/v2/",
    "rootUrl": "https://www.googleapis.com/",
    "discoveryVersion": "v1",
    "resources": {
        "channels": {
            "methods": {
                "stop": {
                    "httpMethod": "POST",
                    "description": "Stops watching resources through this channel.",
                    "flatPath": "channels/stop",
                    "path": "channels/stop",
                    "id": "drive.channels.stop",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.apps.readonly",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.meet.readonly",
                        "https://www.googleapis.com/auth/drive.metadata",
                        "https://www.googleapis.com/auth/drive.metadata.readonly",
                        "https://www.googleapis.com/auth/drive.photos.readonly",
                        "https://www.googleapis.com/auth/drive.readonly"
                    ]
                }
            }
        },
        "replies": {
            "methods": {
                "delete": {
                    "httpMethod": "DELETE",
                    "description": "Deletes a reply.",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.file"
                    ],
                    "flatPath": "files/{fileId}/comments/{commentId}/replies/{replyId}",
                    "id": "drive.replies.delete",
                    "path": "files/{fileId}/comments/{commentId}/replies/{replyId}"
                },
                "patch": {
                    "path": "files/{fileId}/comments/{commentId}/replies/{replyId}",
                    "description": "Updates an existing reply.",
                    "id": "drive.replies.patch",
                    "flatPath": "files/{fileId}/comments/{commentId}/replies/{replyId}",
                    "httpMethod": "PATCH",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.file"
                    ]
                },
                "update": {
                    "id": "drive.replies.update",
                    "description": "Updates an existing reply.",
                    "httpMethod": "PUT",
                    "flatPath": "files/{fileId}/comments/{commentId}/replies/{replyId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.file"
                    ],
                    "path": "files/{fileId}/comments/{commentId}/replies/{replyId}"
                },
                "get": {
                    "flatPath": "files/{fileId}/comments/{commentId}/replies/{replyId}",
                    "httpMethod": "GET",
                    "description": "Gets a reply.",
                    "id": "drive.replies.get",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.meet.readonly",
                        "https://www.googleapis.com/auth/drive.readonly"
                    ],
                    "path": "files/{fileId}/comments/{commentId}/replies/{replyId}"
                },
                "insert": {
                    "path": "files/{fileId}/comments/{commentId}/replies",
                    "id": "drive.replies.insert",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.file"
                    ],
                    "httpMethod": "POST",
                    "flatPath": "files/{fileId}/comments/{commentId}/replies",
                    "description": "Creates a new reply to the given comment."
                },
                "list": {
                    "description": "Lists all of the replies to a comment.",
                    "flatPath": "files/{fileId}/comments/{commentId}/replies",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.meet.readonly",
                        "https://www.googleapis.com/auth/drive.readonly"
                    ],
                    "id": "drive.replies.list",
                    "path": "files/{fileId}/comments/{commentId}/replies",
                    "httpMethod": "GET"
                }
            }
        },
        "children": {
            "methods": {
                "delete": {
                    "path": "files/{folderId}/children/{childId}",
                    "httpMethod": "DELETE",
                    "description": "Removes a child from a folder.",
                    "id": "drive.children.delete",
                    "flatPath": "files/{folderId}/children/{childId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.file"
                    ]
                },
                "get": {
                    "path": "files/{folderId}/children/{childId}",
                    "httpMethod": "GET",
                    "description": "Gets a specific child reference.",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.meet.readonly",
                        "https://www.googleapis.com/auth/drive.metadata",
                        "https://www.googleapis.com/auth/drive.metadata.readonly",
                        "https://www.googleapis.com/auth/drive.photos.readonly",
                        "https://www.googleapis.com/auth/drive.readonly"
                    ],
                    "flatPath": "files/{folderId}/children/{childId}",
                    "id": "drive.children.get"
                },
                "list": {
                    "description": "Lists a folder's children.",
                    "httpMethod": "GET",
                    "id": "drive.children.list",
                    "flatPath": "files/{folderId}/children",
                    "path": "files/{folderId}/children",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.meet.readonly",
                        "https://www.googleapis.com/auth/drive.metadata",
                        "https://www.googleapis.com/auth/drive.metadata.readonly",
                        "https://www.googleapis.com/auth/drive.photos.readonly",
                        "https://www.googleapis.com/auth/drive.readonly"
                    ]
                },
                "insert": {
                    "id": "drive.children.insert",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.file"
                    ],
                    "flatPath": "files/{folderId}/children",
                    "description": "Inserts a file into a folder.",
                    "path": "files/{folderId}/children",
                    "httpMethod": "POST"
                }
            }
        },
        "teamdrives": {
            "methods": {
                "delete": {
                    "path": "teamdrives/{teamDriveId}",
                    "description": "Deprecated: Use `drives.delete` instead.",
                    "flatPath": "teamdrives/{teamDriveId}",
                    "httpMethod": "DELETE",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive"
                    ],
                    "id": "drive.teamdrives.delete"
                },
                "insert": {
                    "scopes": [
                        "https://www.googleapis.com/auth/drive"
                    ],
                    "description": "Deprecated: Use `drives.insert` instead.",
                    "httpMethod": "POST",
                    "path": "teamdrives",
                    "flatPath": "teamdrives",
                    "id": "drive.teamdrives.insert"
                },
                "get": {
                    "description": "Deprecated: Use `drives.get` instead.",
                    "id": "drive.teamdrives.get",
                    "flatPath": "teamdrives/{teamDriveId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.readonly"
                    ],
                    "httpMethod": "GET",
                    "path": "teamdrives/{teamDriveId}"
                },
                "update": {
                    "path": "teamdrives/{teamDriveId}",
                    "description": "Deprecated: Use `drives.update` instead.",
                    "id": "drive.teamdrives.update",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive"
                    ],
                    "flatPath": "teamdrives/{teamDriveId}",
                    "httpMethod": "PUT"
                },
                "list": {
                    "id": "drive.teamdrives.list",
                    "httpMethod": "GET",
                    "description": "Deprecated: Use `drives.list` instead.",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.readonly"
                    ],
                    "path": "teamdrives",
                    "flatPath": "teamdrives"
                }
            }
        },
        "parents": {
            "methods": {
                "insert": {
                    "id": "drive.parents.insert",
                    "httpMethod": "POST",
                    "flatPath": "files/{fileId}/parents",
                    "description": "Adds a parent folder for a file.",
                    "path": "files/{fileId}/parents",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.file"
                    ]
                },
                "list": {
                    "httpMethod": "GET",
                    "flatPath": "files/{fileId}/parents",
                    "path": "files/{fileId}/parents",
                    "id": "drive.parents.list",
                    "description": "Lists a file's parents.",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.meet.readonly",
                        "https://www.googleapis.com/auth/drive.metadata",
                        "https://www.googleapis.com/auth/drive.metadata.readonly",
                        "https://www.googleapis.com/auth/drive.photos.readonly",
                        "https://www.googleapis.com/auth/drive.readonly"
                    ]
                },
                "get": {
                    "flatPath": "files/{fileId}/parents/{parentId}",
                    "path": "files/{fileId}/parents/{parentId}",
                    "httpMethod": "GET",
                    "description": "Gets a specific parent reference.",
                    "id": "drive.parents.get",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.meet.readonly",
                        "https://www.googleapis.com/auth/drive.metadata",
                        "https://www.googleapis.com/auth/drive.metadata.readonly",
                        "https://www.googleapis.com/auth/drive.photos.readonly",
                        "https://www.googleapis.com/auth/drive.readonly"
                    ]
                },
                "delete": {
                    "httpMethod": "DELETE",
                    "description": "Removes a parent from a file.",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.file"
                    ],
                    "path": "files/{fileId}/parents/{parentId}",
                    "id": "drive.parents.delete",
                    "flatPath": "files/{fileId}/parents/{parentId}"
                }
            }
        },
        "files": {
            "methods": {
                "emptyTrash": {
                    "path": "files/trash",
                    "httpMethod": "DELETE",
                    "description": "Permanently deletes all of the user's trashed files.",
                    "flatPath": "files/trash",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive"
                    ],
                    "id": "drive.files.emptyTrash"
                },
                "trash": {
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.apps.readonly",
                        "https://www.googleapis.com/auth/drive.file"
                    ],
                    "description": "Moves a file to the trash. The currently authenticated user must own the file or be at least a `fileOrganizer` on the parent for shared drive files.",
                    "path": "files/{fileId}/trash",
                    "httpMethod": "POST",
                    "flatPath": "files/{fileId}/trash",
                    "id": "drive.files.trash"
                },
                "update": {
                    "supportsMediaUpload": true,
                    "path": "files/{fileId}",
                    "httpMethod": "PUT",
                    "flatPath": "files/{fileId}",
                    "description": " Updates a file's metadata, content, or both. When calling this method, only populate fields in the request that you want to modify. When updating fields, some fields might be changed automatically, such as `modifiedDate`. This method supports patch semantics. This method supports an */upload* URI and accepts uploaded media with the following characteristics: - *Maximum file size:* 5,120 GB - *Accepted Media MIME types:* `*/*` (Specify a valid MIME type, rathe[...]",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.apps.readonly",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.metadata",
                        "https://www.googleapis.com/auth/drive.scripts"
                    ],
                    "id": "drive.files.update"
                },
                "list": {
                    "id": "drive.files.list",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.apps.readonly",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.meet.readonly",
                        "https://www.googleapis.com/auth/drive.metadata",
                        "https://www.googleapis.com/auth/drive.metadata.readonly",
                        "https://www.googleapis.com/auth/drive.photos.readonly",
                        "https://www.googleapis.com/auth/drive.readonly"
                    ],
                    "description": " Lists the user's files. For more information, see [Search for files and folders](/workspace/drive/api/guides/search-files). This method accepts the `q` parameter, which is a search query combining one or more search terms. This method returns *all* files by default, including trashed files. If you don't want trashed files to appear in the list, use the `trashed=false` query parameter to remove trashed files from the results.",
                    "path": "files",
                    "flatPath": "files",
                    "httpMethod": "GET"
                },
                "delete": {
                    "flatPath": "files/{fileId}",
                    "id": "drive.files.delete",
                    "path": "files/{fileId}",
                    "httpMethod": "DELETE",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.file"
                    ],
                    "description": "Permanently deletes a file owned by the user without moving it to the trash. If the file belongs to a shared drive, the user must be an `organizer` on the parent folder. If the target is a folder, all descendants owned by the user are also deleted."
                },
                "insert": {
                    "id": "drive.files.insert",
                    "description": " Inserts a new file. This method supports an */upload* URI and accepts uploaded media with the following characteristics: - *Maximum file size:* 5,120 GB - *Accepted Media MIME types:*`*/*` Note: Specify a valid MIME type, rather than the literal `*/*` value. The literal `*/*` is only used to indicate that any valid MIME type can be uploaded. For more information on uploading files, see [Upload file data](/workspace/drive/api/guides/manage-uploads). Apps creat[...]",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.apps.readonly",
                        "https://www.googleapis.com/auth/drive.file"
                    ],
                    "supportsMediaUpload": true,
                    "path": "files",
                    "httpMethod": "POST",
                    "flatPath": "files"
                },
                "touch": {
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.apps.readonly",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.metadata"
                    ],
                    "path": "files/{fileId}/touch",
                    "httpMethod": "POST",
                    "description": "Set the file's updated time to the current server time.",
                    "flatPath": "files/{fileId}/touch",
                    "id": "drive.files.touch"
                },
                "copy": {
                    "description": "Creates a copy of the specified file.",
                    "httpMethod": "POST",
                    "flatPath": "files/{fileId}/copy",
                    "id": "drive.files.copy",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.apps.readonly",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.photos.readonly"
                    ],
                    "path": "files/{fileId}/copy"
                },
                "generateIds": {
                    "httpMethod": "GET",
                    "id": "drive.files.generateIds",
                    "flatPath": "files/generateIds",
                    "description": "Generates a set of file IDs which can be provided in insert or copy requests.",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.file"
                    ],
                    "path": "files/generateIds"
                },
                "watch": {
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.meet.readonly",
                        "https://www.googleapis.com/auth/drive.metadata",
                        "https://www.googleapis.com/auth/drive.metadata.readonly",
                        "https://www.googleapis.com/auth/drive.photos.readonly",
                        "https://www.googleapis.com/auth/drive.readonly"
                    ],
                    "path": "files/{fileId}/watch",
                    "supportsSubscription": true,
                    "description": "Subscribes to changes to a file.",
                    "id": "drive.files.watch",
                    "httpMethod": "POST",
                    "flatPath": "files/{fileId}/watch"
                },
                "export": {
                    "supportsMediaDownload": true,
                    "id": "drive.files.export",
                    "path": "files/{fileId}/export",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.meet.readonly",
                        "https://www.googleapis.com/auth/drive.readonly"
                    ],
                    "flatPath": "files/{fileId}/export",
                    "description": "Exports a Google Workspace document to the requested MIME type and returns exported byte content. Note that the exported content is limited to 10MB.",
                    "useMediaDownloadService": true,
                    "httpMethod": "GET"
                },
                "patch": {
                    "flatPath": "files/{fileId}",
                    "description": "Updates a file's metadata and/or content. When calling this method, only populate fields in the request that you want to modify. When updating fields, some fields might change automatically, such as modifiedDate. This method supports patch semantics.",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.apps.readonly",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.metadata",
                        "https://www.googleapis.com/auth/drive.scripts"
                    ],
                    "path": "files/{fileId}",
                    "id": "drive.files.patch",
                    "httpMethod": "PATCH"
                },
                "get": {
                    "httpMethod": "GET",
                    "description": " Gets a file's metadata or content by ID. If you provide the URL parameter `alt=media`, then the response includes the file contents in the response body. Downloading content with `alt=media` only works if the file is stored in Drive. To download Google Docs, Sheets, and Slides use [`files.export`](/workspace/drive/api/reference/rest/v2/files/export) instead. For more information, see [Download & export files](/workspace/drive/api/guides/manage-downloads).",
                    "path": "files/{fileId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.meet.readonly",
                        "https://www.googleapis.com/auth/drive.metadata",
                        "https://www.googleapis.com/auth/drive.metadata.readonly",
                        "https://www.googleapis.com/auth/drive.photos.readonly",
                        "https://www.googleapis.com/auth/drive.readonly"
                    ],
                    "useMediaDownloadService": true,
                    "id": "drive.files.get",
                    "supportsSubscription": true,
                    "supportsMediaDownload": true,
                    "flatPath": "files/{fileId}"
                },
                "listLabels": {
                    "path": "files/{fileId}/listLabels",
                    "flatPath": "files/{fileId}/listLabels",
                    "httpMethod": "GET",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.meet.readonly",
                        "https://www.googleapis.com/auth/drive.metadata",
                        "https://www.googleapis.com/auth/drive.metadata.readonly",
                        "https://www.googleapis.com/auth/drive.readonly"
                    ],
                    "id": "drive.files.listLabels",
                    "description": "Lists the labels on a file."
                },
                "modifyLabels": {
                    "id": "drive.files.modifyLabels",
                    "path": "files/{fileId}/modifyLabels",
                    "flatPath": "files/{fileId}/modifyLabels",
                    "description": "Modifies the set of labels applied to a file. Returns a list of the labels that were added or modified.",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.metadata"
                    ],
                    "httpMethod": "POST"
                },
                "untrash": {
                    "flatPath": "files/{fileId}/untrash",
                    "id": "drive.files.untrash",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.apps.readonly",
                        "https://www.googleapis.com/auth/drive.file"
                    ],
                    "httpMethod": "POST",
                    "description": "Restores a file from the trash. The currently authenticated user must own the file or be at least a `fileOrganizer` on the parent for shared drive files.",
                    "path": "files/{fileId}/untrash"
                }
            }
        },
        "drives": {
            "methods": {
                "get": {
                    "description": "Gets a shared drive's metadata by ID.",
                    "httpMethod": "GET",
                    "flatPath": "drives/{driveId}",
                    "path": "drives/{driveId}",
                    "id": "drive.drives.get",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.readonly"
                    ]
                },
                "insert": {
                    "description": "Creates a new shared drive.",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive"
                    ],
                    "id": "drive.drives.insert",
                    "path": "drives",
                    "httpMethod": "POST",
                    "flatPath": "drives"
                },
                "unhide": {
                    "id": "drive.drives.unhide",
                    "httpMethod": "POST",
                    "path": "drives/{driveId}/unhide",
                    "description": "Restores a shared drive to the default view.",
                    "flatPath": "drives/{driveId}/unhide",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive"
                    ]
                },
                "list": {
                    "flatPath": "drives",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.readonly"
                    ],
                    "description": " Lists the user's shared drives. This method accepts the `q` parameter, which is a search query combining one or more search terms. For more information, see the [Search for shared drives](/workspace/drive/api/guides/search-shareddrives) guide.",
                    "httpMethod": "GET",
                    "path": "drives",
                    "id": "drive.drives.list"
                },
                "hide": {
                    "flatPath": "drives/{driveId}/hide",
                    "description": "Hides a shared drive from the default view.",
                    "path": "drives/{driveId}/hide",
                    "httpMethod": "POST",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive"
                    ],
                    "id": "drive.drives.hide"
                },
                "update": {
                    "description": "Updates the metadata for a shared drive.",
                    "httpMethod": "PUT",
                    "id": "drive.drives.update",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive"
                    ],
                    "path": "drives/{driveId}",
                    "flatPath": "drives/{driveId}"
                },
                "delete": {
                    "httpMethod": "DELETE",
                    "id": "drive.drives.delete",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive"
                    ],
                    "description": "Permanently deletes a shared drive for which the user is an `organizer`. The shared drive cannot contain any untrashed items.",
                    "flatPath": "drives/{driveId}",
                    "path": "drives/{driveId}"
                }
            }
        },
        "changes": {
            "methods": {
                "watch": {
                    "flatPath": "changes/watch",
                    "description": "Subscribe to changes for a user.",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.apps.readonly",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.meet.readonly",
                        "https://www.googleapis.com/auth/drive.metadata",
                        "https://www.googleapis.com/auth/drive.metadata.readonly",
                        "https://www.googleapis.com/auth/drive.photos.readonly",
                        "https://www.googleapis.com/auth/drive.readonly"
                    ],
                    "path": "changes/watch",
                    "supportsSubscription": true,
                    "httpMethod": "POST",
                    "id": "drive.changes.watch"
                },
                "list": {
                    "flatPath": "changes",
                    "path": "changes",
                    "supportsSubscription": true,
                    "httpMethod": "GET",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.apps.readonly",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.meet.readonly",
                        "https://www.googleapis.com/auth/drive.metadata",
                        "https://www.googleapis.com/auth/drive.metadata.readonly",
                        "https://www.googleapis.com/auth/drive.photos.readonly",
                        "https://www.googleapis.com/auth/drive.readonly"
                    ],
                    "description": "Lists the changes for a user or shared drive.",
                    "id": "drive.changes.list"
                },
                "get": {
                    "description": "Deprecated: Use `changes.getStartPageToken` and `changes.list` to retrieve recent changes.",
                    "flatPath": "changes/{changeId}",
                    "path": "changes/{changeId}",
                    "httpMethod": "GET",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.apps.readonly",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.meet.readonly",
                        "https://www.googleapis.com/auth/drive.metadata",
                        "https://www.googleapis.com/auth/drive.metadata.readonly",
                        "https://www.googleapis.com/auth/drive.photos.readonly",
                        "https://www.googleapis.com/auth/drive.readonly"
                    ],
                    "id": "drive.changes.get"
                },
                "getStartPageToken": {
                    "id": "drive.changes.getStartPageToken",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.apps.readonly",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.meet.readonly",
                        "https://www.googleapis.com/auth/drive.metadata",
                        "https://www.googleapis.com/auth/drive.metadata.readonly",
                        "https://www.googleapis.com/auth/drive.photos.readonly",
                        "https://www.googleapis.com/auth/drive.readonly"
                    ],
                    "description": "Gets the starting pageToken for listing future changes.",
                    "httpMethod": "GET",
                    "flatPath": "changes/startPageToken",
                    "path": "changes/startPageToken"
                }
            }
        },
        "revisions": {
            "methods": {
                "delete": {
                    "httpMethod": "DELETE",
                    "flatPath": "files/{fileId}/revisions/{revisionId}",
                    "description": "Permanently deletes a file version. You can only delete revisions for files with binary content, like images or videos. Revisions for other files, like Google Docs or Sheets, and the last remaining file version can't be deleted.",
                    "path": "files/{fileId}/revisions/{revisionId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.file"
                    ],
                    "id": "drive.revisions.delete"
                },
                "get": {
                    "httpMethod": "GET",
                    "flatPath": "files/{fileId}/revisions/{revisionId}",
                    "description": "Gets a specific revision.",
                    "path": "files/{fileId}/revisions/{revisionId}",
                    "id": "drive.revisions.get",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.meet.readonly",
                        "https://www.googleapis.com/auth/drive.metadata",
                        "https://www.googleapis.com/auth/drive.metadata.readonly",
                        "https://www.googleapis.com/auth/drive.photos.readonly",
                        "https://www.googleapis.com/auth/drive.readonly"
                    ]
                },
                "patch": {
                    "description": "Updates a revision.",
                    "path": "files/{fileId}/revisions/{revisionId}",
                    "httpMethod": "PATCH",
                    "id": "drive.revisions.patch",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.file"
                    ],
                    "flatPath": "files/{fileId}/revisions/{revisionId}"
                },
                "list": {
                    "httpMethod": "GET",
                    "description": "Lists a file's revisions. **Important:** The list of revisions returned by this method might be incomplete for files with a large revision history, including frequently edited Google Docs, Sheets, and Slides. Older revisions might be omitted from the response, meaning the first revision returned may not be the oldest existing revision. The revision history visible in the Workspace editor user interface might be more complete than the list returned by the API."[...]",
                    "path": "files/{fileId}/revisions",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.meet.readonly",
                        "https://www.googleapis.com/auth/drive.metadata",
                        "https://www.googleapis.com/auth/drive.metadata.readonly",
                        "https://www.googleapis.com/auth/drive.photos.readonly",
                        "https://www.googleapis.com/auth/drive.readonly"
                    ],
                    "id": "drive.revisions.list",
                    "flatPath": "files/{fileId}/revisions"
                },
                "update": {
                    "description": "Updates a revision.",
                    "flatPath": "files/{fileId}/revisions/{revisionId}",
                    "httpMethod": "PUT",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.file"
                    ],
                    "id": "drive.revisions.update",
                    "path": "files/{fileId}/revisions/{revisionId}"
                }
            }
        },
        "about": {
            "methods": {
                "get": {
                    "httpMethod": "GET",
                    "path": "about",
                    "flatPath": "about",
                    "description": "Gets the information about the current user along with Drive API settings",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.metadata",
                        "https://www.googleapis.com/auth/drive.metadata.readonly",
                        "https://www.googleapis.com/auth/drive.photos.readonly",
                        "https://www.googleapis.com/auth/drive.readonly"
                    ],
                    "id": "drive.about.get"
                }
            }
        },
        "apps": {
            "methods": {
                "get": {
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.apps.readonly",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.metadata",
                        "https://www.googleapis.com/auth/drive.metadata.readonly",
                        "https://www.googleapis.com/auth/drive.readonly"
                    ],
                    "description": "Gets a specific app.",
                    "httpMethod": "GET",
                    "flatPath": "apps/{appId}",
                    "id": "drive.apps.get",
                    "path": "apps/{appId}"
                },
                "list": {
                    "description": "Lists a user's installed apps.",
                    "path": "apps",
                    "httpMethod": "GET",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive.apps.readonly"
                    ],
                    "id": "drive.apps.list",
                    "flatPath": "apps"
                }
            }
        },
        "permissions": {
            "methods": {
                "patch": {
                    "id": "drive.permissions.patch",
                    "path": "files/{fileId}/permissions/{permissionId}",
                    "description": "Updates a permission using patch semantics. **Warning:** Concurrent permissions operations on the same file are not supported; only the last update is applied.",
                    "httpMethod": "PATCH",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.file"
                    ],
                    "flatPath": "files/{fileId}/permissions/{permissionId}"
                },
                "get": {
                    "path": "files/{fileId}/permissions/{permissionId}",
                    "id": "drive.permissions.get",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.meet.readonly",
                        "https://www.googleapis.com/auth/drive.metadata",
                        "https://www.googleapis.com/auth/drive.metadata.readonly",
                        "https://www.googleapis.com/auth/drive.photos.readonly",
                        "https://www.googleapis.com/auth/drive.readonly"
                    ],
                    "httpMethod": "GET",
                    "flatPath": "files/{fileId}/permissions/{permissionId}",
                    "description": "Gets a permission by ID."
                },
                "update": {
                    "flatPath": "files/{fileId}/permissions/{permissionId}",
                    "path": "files/{fileId}/permissions/{permissionId}",
                    "httpMethod": "PUT",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.file"
                    ],
                    "description": "Updates a permission. **Warning:** Concurrent permissions operations on the same file are not supported; only the last update is applied.",
                    "id": "drive.permissions.update"
                },
                "list": {
                    "id": "drive.permissions.list",
                    "httpMethod": "GET",
                    "flatPath": "files/{fileId}/permissions",
                    "description": "Lists a file's or shared drive's permissions.",
                    "path": "files/{fileId}/permissions",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.meet.readonly",
                        "https://www.googleapis.com/auth/drive.metadata",
                        "https://www.googleapis.com/auth/drive.metadata.readonly",
                        "https://www.googleapis.com/auth/drive.photos.readonly",
                        "https://www.googleapis.com/auth/drive.readonly"
                    ]
                },
                "getIdForEmail": {
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.apps.readonly",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.metadata",
                        "https://www.googleapis.com/auth/drive.metadata.readonly",
                        "https://www.googleapis.com/auth/drive.photos.readonly",
                        "https://www.googleapis.com/auth/drive.readonly"
                    ],
                    "description": "Returns the permission ID for an email address.",
                    "flatPath": "permissionIds/{email}",
                    "path": "permissionIds/{email}",
                    "id": "drive.permissions.getIdForEmail",
                    "httpMethod": "GET"
                },
                "delete": {
                    "path": "files/{fileId}/permissions/{permissionId}",
                    "id": "drive.permissions.delete",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.file"
                    ],
                    "flatPath": "files/{fileId}/permissions/{permissionId}",
                    "httpMethod": "DELETE",
                    "description": "Deletes a permission from a file or shared drive. **Warning:** Concurrent permissions operations on the same file are not supported; only the last update is applied."
                },
                "insert": {
                    "flatPath": "files/{fileId}/permissions",
                    "httpMethod": "POST",
                    "id": "drive.permissions.insert",
                    "path": "files/{fileId}/permissions",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.file"
                    ],
                    "description": "Inserts a permission for a file or shared drive. **Warning:** Concurrent permissions operations on the same file are not supported; only the last update is applied."
                }
            }
        },
        "properties": {
            "methods": {
                "delete": {
                    "id": "drive.properties.delete",
                    "httpMethod": "DELETE",
                    "description": "Deletes a property.",
                    "flatPath": "files/{fileId}/properties/{propertyKey}",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.metadata"
                    ],
                    "path": "files/{fileId}/properties/{propertyKey}"
                },
                "patch": {
                    "id": "drive.properties.patch",
                    "path": "files/{fileId}/properties/{propertyKey}",
                    "description": "Updates a property.",
                    "flatPath": "files/{fileId}/properties/{propertyKey}",
                    "httpMethod": "PATCH",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.metadata"
                    ]
                },
                "insert": {
                    "flatPath": "files/{fileId}/properties",
                    "path": "files/{fileId}/properties",
                    "httpMethod": "POST",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.metadata"
                    ],
                    "id": "drive.properties.insert",
                    "description": "Adds a property to a file, or updates it if it already exists."
                },
                "get": {
                    "description": "Gets a property by its key.",
                    "flatPath": "files/{fileId}/properties/{propertyKey}",
                    "httpMethod": "GET",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.meet.readonly",
                        "https://www.googleapis.com/auth/drive.metadata",
                        "https://www.googleapis.com/auth/drive.metadata.readonly",
                        "https://www.googleapis.com/auth/drive.photos.readonly",
                        "https://www.googleapis.com/auth/drive.readonly"
                    ],
                    "id": "drive.properties.get",
                    "path": "files/{fileId}/properties/{propertyKey}"
                },
                "update": {
                    "id": "drive.properties.update",
                    "flatPath": "files/{fileId}/properties/{propertyKey}",
                    "description": "Updates a property.",
                    "path": "files/{fileId}/properties/{propertyKey}",
                    "httpMethod": "PUT",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.metadata"
                    ]
                },
                "list": {
                    "description": "Lists a file's properties.",
                    "flatPath": "files/{fileId}/properties",
                    "path": "files/{fileId}/properties",
                    "httpMethod": "GET",
                    "id": "drive.properties.list",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.appdata",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.meet.readonly",
                        "https://www.googleapis.com/auth/drive.metadata",
                        "https://www.googleapis.com/auth/drive.metadata.readonly",
                        "https://www.googleapis.com/auth/drive.photos.readonly",
                        "https://www.googleapis.com/auth/drive.readonly"
                    ]
                }
            }
        },
        "comments": {
            "methods": {
                "list": {
                    "flatPath": "files/{fileId}/comments",
                    "id": "drive.comments.list",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.meet.readonly",
                        "https://www.googleapis.com/auth/drive.readonly"
                    ],
                    "path": "files/{fileId}/comments",
                    "httpMethod": "GET",
                    "description": "Lists a file's comments."
                },
                "insert": {
                    "httpMethod": "POST",
                    "id": "drive.comments.insert",
                    "description": "Creates a new comment on the given file.",
                    "flatPath": "files/{fileId}/comments",
                    "path": "files/{fileId}/comments",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.file"
                    ]
                },
                "patch": {
                    "flatPath": "files/{fileId}/comments/{commentId}",
                    "path": "files/{fileId}/comments/{commentId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.file"
                    ],
                    "description": "Updates an existing comment.",
                    "id": "drive.comments.patch",
                    "httpMethod": "PATCH"
                },
                "update": {
                    "description": "Updates an existing comment.",
                    "id": "drive.comments.update",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.file"
                    ],
                    "flatPath": "files/{fileId}/comments/{commentId}",
                    "path": "files/{fileId}/comments/{commentId}",
                    "httpMethod": "PUT"
                },
                "delete": {
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.file"
                    ],
                    "description": "Deletes a comment.",
                    "flatPath": "files/{fileId}/comments/{commentId}",
                    "id": "drive.comments.delete",
                    "httpMethod": "DELETE",
                    "path": "files/{fileId}/comments/{commentId}"
                },
                "get": {
                    "id": "drive.comments.get",
                    "description": "Gets a comment by ID.",
                    "path": "files/{fileId}/comments/{commentId}",
                    "flatPath": "files/{fileId}/comments/{commentId}",
                    "scopes": [
                        "https://www.googleapis.com/auth/drive",
                        "https://www.googleapis.com/auth/drive.file",
                        "https://www.googleapis.com/auth/drive.meet.readonly",
                        "https://www.googleapis.com/auth/drive.readonly"
                    ],
                    "httpMethod": "GET"
                }
            }
        }
    },
    "documentationLink": "https://developers.google.com/workspace/drive/",
    "revision": "20260201",
    "id": "drive:v2",
    "version": "v2",
    "description": "The Google Drive API allows clients to access resources from Google Drive.",
    "kind": "discovery#restDescription",
    "ownerName": "Google",
    "ownerDomain": "google.com",
    "protocol": "rest",
    "title": "Google Drive API",
    "baseUrl": "https://www.googleapis.com/drive/v2/"
}